lane :test do
  jira_issue_features(
    jira_base_url: "https://your-domain.atlassian.net",
    issue_id: "IOS-405",
    target_column_name: "REVIEW",
    email: "your-email@example.com",
    api_token: "your-api-token",
    comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget venenatis elit. Duis eu justo eget augue iaculis fermentum. Sed semper quam laoreet nisi egestas at posuere augue semper."
  )
end
